### ISSUE TITLE
Reference categories

### ISSUE THREAD

**Issue by esyriani** [geodes-sms/relis#1]
There is a problem with the labels and the pages displayed of the reference categories.
In project User interaction and interface in MDE, the configuration had no default values for the hciModel and mdeModel dynamic lists. I see 3 reference categories in the menu: HCI model, hciModel and mdeModel. Should be "HCI model" and "MDE model".

**Comment by esyriani** [comment]
Is this solved by issue #17 ?

**Comment by bricemike1** [comment]
Yes this is solved by #17
