### ISSUE TITLE
Hide partial screening information from reviewers who haven't finish their assignments

### ISSUE THREAD

**Issue by david-istvan** [geodes-sms/relis#101]
Learning about other reviewers' preferences introduces threats to internal validity as it may bias the judgment of reviewers who haven't finished their assignments yet.

Demonstrated in the figure below (at about 40% overall progress). Highlighted the critical information.

![image](https://user-images.githubusercontent.com/2520125/224287407-3ca1cbf5-827e-44be-86e3-e43e78f72063.png)

Suggestion: hide this panel from those who haven't finished their reviews yet.

**Comment by esyriani** [comment]
It is actually useful to see this info when doing multiple iterations of screening and to monitor the statistics in real-time.
