### ISSUE TITLE
Feature: Reviewers can add missing abstract

### ISSUE THREAD

**Issue by BentleyJOakes** [geodes-sms/relis#106]
**Is your feature request related to a problem? Please describe.**
Related to [abstract missing issue](https://github.com/geodes-sms/relis/issues/105).

The abstracts are sometimes missing, slowing down the screening process.

**Describe the solution you'd like**
Perhaps if the abstract is missing, a reviewer should be able to add an abstract. This would save time for the following reviewers. Uploading a PDF may also assist the review process.

Note that it should be emphasized that the text provided should be only cut-paste by the reviewer with no further information to avoid contamination.

**Comment by esyriani** [comment]
You can already do that by editing the paper in question by following these steps:
1. Go to the homepage of your project (click the house icon at the bottom of the menu)
2. Go to Papers > All
3. Search the paper by Key or title
4. Click Edit
5. Add missing or correct information
6. Click Save
