### ISSUE TITLE
Stored Procedures incomplete

### ISSUE THREAD

**Issue by dhofstetter** [geodes-sms/relis#13]
**Describe the bug**
After a fresh installation and creation of a new user in ReLiS. I logged in with the new User and tried the nav option "Homepage Settings" which lead me to the following error: 
```
A Database Error Occurred
Error Number: 1305

PROCEDURE relisDB_001.get_list_info does not exist

CALL get_list_info(0,0,'' )

Filename: models/DBConnection_mdl.php

Line Number: 971
```

**To Reproduce**
1. Setup ReLiS
2. Create a new User using the admin user
3. Log in using the new user
4. Point to "Homepage Settings"

**Expected behavior**
Homepage Settings page should open up, or an appropriate message if this action is forbidden for non admin users.

**Comment by esyriani** [comment]
Cannot reproduce this error anymore.
