### ISSUE TITLE
broken link of papers in screening

### ISSUE THREAD

**Issue by esyriani** [geodes-sms/relis#16]
**Describe the bug**
When screening articles, the link to the PDF of the article is wrongly prefixed by http://relis.iro.umontreal.ca/relis/manager/

**To Reproduce**
1. Go to the screening page of an article
2. Click on the PDF icon

**Expected behavior**
Should go the URL entered in the article link.

**Desktop (please complete the following information):**
 - Browser: Firefox

**Comment by bricemike1** [comment]
I've not been able to reproduce this bug. Could you attach a screenshot, and the BibTeX of the paper used for testing.

**Comment by esyriani** [comment]
Go to the Language Composition project. There is one paper assigned to my user for screening. When I am screening that paper, clicking on the PDF icon produces this error.
The bibtex is :

@ARTICLE{Landin1966, author = {{L}andin, {P}eter {J}.}, journal = {{C}ommunications of {ACM}}, title = {{T}he next 700% programming languages}, year = {1966}, note = {Some note}, note = {Some note}, paper = {www.google.com} }

When I click on the icon it redirects me to: http://relis.iro.umontreal.ca/relis/manager/www.google.com

**Comment by bricemike1** [comment]
Fixed

**Comment by esyriani** [comment]
During screening, some papers have a link that starts with https// which breaks the link.
For example, in project Language Composition, the paper Athanasopoulos2019 has the correct doi in the bibtexKey column https://dx.doi.org/10.1007/978-3-030-22888-0_3 but the PDF link redirects to https//dx.doi.org/10.1007/978-3-030-22888-0_3
This happens to a lot of papers, but not all.

**Comment by bricemike1** [comment]
Should be fixed now!
