### ISSUE TITLE
Unknown reference category

### ISSUE THREAD

**Issue by esyriani** [geodes-sms/relis#17]
**Describe the bug**
There is an unknown reference category in the classification phase.

**To Reproduce**
1. Go to Project Language_Composition
2. Go to Classification
3. Click on Reference Categories
4. See the tools_carateristic category that I never defined.
5. Clicking on it redirects to http://relis.iro.umontreal.ca/auth/.html

**Expected behavior**
That category should not be there.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Firefox

**Comment by bricemike1** [comment]
Fixed. There was an erro in the fuction cleaning previous installation of a project, some reference categories was not deleted.
