### ISSUE TITLE
Empty classification table

### ISSUE THREAD

**Issue by esyriani** [geodes-sms/relis#18]
**Describe the bug**
The classification result table does not show the data I entered when I did the classification of a paper.

**To Reproduce**
1. Go to Project Language_Composition
2. Go to Classification
3. Click on Result > Table
4. It shows the paper I have classified, but all the row has no data except for the note.

**Expected behavior**
It should show all the data I entered. If you click on the paper, you will see the data is there.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Firefox

**Additional context**
![image](https://user-images.githubusercontent.com/8313663/78687777-8941c980-78c2-11ea-995c-58c30e62af35.png)

![image](https://user-images.githubusercontent.com/8313663/78687860-9c549980-78c2-11ea-9723-783bd6d88c20.png)

**Comment by bricemike1** [comment]
Problem solved, There was an issue in a stored procedure used to display classifications
