### ISSUE TITLE
Adding one paper from BibTeX not working

### ISSUE THREAD

**Issue by esyriani** [geodes-sms/relis#20]
**Describe the bug**
I try to enter the a paper manually by BibTeX. It reports an internal error.

**To Reproduce**
1. Go to the Project homepage (my project is Language Composition)
2. Click on Papers > All
3. Click on Add BibTeX
4. Write this reference:
@ARTICLE{Test2020,
  author = {Test, Test},
  journal = {Journal Test},
  title = {Title Test},
  year = {2020},
  number = {1},
  pages = {1--2},
  volume = {1},
  doi = {www.google.com},
  paper = {http://dx.doi.org/www.google.com}
}
5. Click Submit

**Expected behavior**
Should add the paper with no errors.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Firefox

**Additional context**
![image](https://user-images.githubusercontent.com/8313663/78689768-b2fbf000-78c4-11ea-9a73-a1f7950477f6.png)

**Comment by bricemike1** [comment]
The bug is resolved. There was an issue in the function managing call to Bibler
