### ISSUE TITLE
Subcategories not saved

### ISSUE THREAD

**Issue by esyriani** [geodes-sms/relis#22]
**Describe the bug**
My classification scheme as a subcategory:
```
Simple tool "Tool support" * [1] : bool {
  Simple tool_name "Tool name" : string
}
```
When I classify a paper, I can set the values of the subcategory. But when I save it it is not stored.

**To Reproduce**
1. Go to Language Composition project
2. Go to the Classification phase
3. Click on Results > Table
4. Click on the paper Landin1966 -
5. If you Edit the classification you can set Tool support and Tool name
6. When you save the classification, the values are gone.

**Expected behavior**
The values of subcategories (recursively) should be saved.

**Screenshots**
##### Setting the subcategory values
![image](https://user-images.githubusercontent.com/8313663/79127141-58a0da80-7d6f-11ea-8d2e-0bf96b2cf106.png)
##### It is stored before saving
![image](https://user-images.githubusercontent.com/8313663/79127122-4fb00900-7d6f-11ea-9b7f-479cbdf4966a.png)
##### After save, the values are gone
![image](https://user-images.githubusercontent.com/8313663/79127193-7110f500-7d6f-11ea-8c23-38b9b2008edf.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser Firefox

**Additional context**
This is related to issue #21

**Comment by bricemike1** [comment]
Fixed

**Comment by esyriani** [comment]
Yes I see it now that it is saved. But subcategories do not appear in the result table.
![image](https://user-images.githubusercontent.com/8313663/80017548-c56c5100-84a2-11ea-9231-b2d0e0731f0a.png)
