### ISSUE TITLE
Broken link on screen_paper view.

### ISSUE THREAD

**Issue by kolmogorov-fan-account** [geodes-sms/relis#28]
**Describe the bug**

The link to the paper on the `screen_paper` view is broken.

<img width="1302" alt="image" src="https://user-images.githubusercontent.com/1782845/82088973-b69f4580-96c0-11ea-8c36-cff9d2a63b26.png">

The generated HTML is the following
```html
<a href="//http://dx.doi.org/10.1145/3180155.3180250" target="black" style="color:#aa7777;">
  <img src="http://relis.iro.umontreal.ca/cside/images/pdf.jpg">
</a>
```

The issue is that for some reason the URL is prefixed by `//`.

Other views like `display_paper_screen` do not exhibit this issue.

**Expected behavior**

The generated URL is `http://dx.doi.org/10.1145/3180155.3180250`.

**Comment by esyriani** [comment]
Related to #16

**Comment by bricemike1** [comment]
Should be fixed now.
