### ISSUE TITLE
Wrong calculation of the gauges on the Screening Dashboard

### ISSUE THREAD

**Issue by david-istvan** [geodes-sms/relis#34]
**Describe the bug**
The visualized ratio is calculated as `(screened-conflics)/all`. (In both views: My progress and Overall progress.)

**Expected behavior**
The visualized ratio should be calculated as `screened/all`.

**Screenshots**
![image](https://user-images.githubusercontent.com/2520125/112576535-dca97200-8dc8-11eb-9aa8-775093c93904.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Chrome
 - Version: 89.0.4389.90 (Official Build) (64-bit)

**Comment by esyriani** [comment]
It depends on the semantics of "screened". Here, a screened paper means that the reviewer who was assigned to it has given a decision. It could be argued that a paper is "screened" when it has received all the required reviews and is free of conflicts. But that is not the case .
