### ISSUE TITLE
Error: add a new user to the project

### ISSUE THREAD

**Issue by DaJaime** [geodes-sms/relis#35]
**Describe the bug**
An error appears when I try to add a user to my project.

**To Reproduce**
1. I created a new project.
2. Click on 'Users' in the menu.
3. Click on the green button "+" to add a new user to the project.
4. An error page is displayed.

**Screenshots**
![Screen1](https://user-images.githubusercontent.com/33934807/112871714-d4e71780-90bf-11eb-9060-7465363f9837.PNG)
![Screen2](https://user-images.githubusercontent.com/33934807/112871723-d7e20800-90bf-11eb-86c6-806a032b0735.PNG)
![Screen3](https://user-images.githubusercontent.com/33934807/112871728-da446200-90bf-11eb-8c25-3afc38baa65e.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave (Chromium) & Microsoft Edge

**Comment by esyriani** [comment]
We migrated to PHP 7 and corrected syntax problems w.r.t. function parameters initialized as empty strings but used as Corrected by initializing them to [].
