### ISSUE TITLE
Error message when viewing the history of a paper

### ISSUE THREAD

**Issue by esyriani** [geodes-sms/relis#36]
**Describe the bug**
When we go to a paper to view its history (e.g., log of screening), an error message appears at the top of the page. It is actually a problem on line 4182 in [/relis_app/controllers/relis/Manager.php](https://github.com/geodes-sms/relis/blob/master/relis_app/controllers/relis/Manager.php). The code is: `if(count($value['val2']>1)){` but count takes a list, not a condition.

**To Reproduce**
1. Go to a screening phase
2. Click on Papers in this phase > Included
3. Click on the title of one paper
4. See error at the top of the page

**Screenshots**
![image](https://user-images.githubusercontent.com/8313663/112993027-c0923180-9136-11eb-9273-2a4a2d00b7fb.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: in production

**Comment by PUR2212** [comment]
Duplicate as issue #44
Replace 
if(count($value['val2']>1)) 
to 
if(count($value['val2'])>1)
