### ISSUE TITLE
Cannot create manual assignments as a Project admin

### ISSUE THREAD

**Issue by david-istvan** [geodes-sms/relis#38]
**Describe the bug**
@esyriani was able to create manual assignments as a Project admin in the same project. This right might be assigned to a system role rather than a project role.

**Expected behavior**
A Project admin should be able to create manual assignments.

**Comment by esyriani** [comment]
To clarify, the issue is that a Project Manager cannot add reviewers to a paper already screened. Only Administrators can. Project Managers should be able to do so. [See the Access roles per right matrix in the Help](http://relis.iro.umontreal.ca/auth/help_det/6)
